// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"sagooiot/internal/dao/internal"
)

// sysJobLogDao is the data access object for the table sys_job_log.
// You can define custom methods on it to extend its functionality as needed.
type sysJobLogDao struct {
	*internal.SysJobLogDao
}

var (
	// SysJobLog is a globally accessible object for table sys_job_log operations.
	SysJobLog = sysJobLogDao{internal.NewSysJobLogDao()}
)

// Add your custom methods and functionality below.
